name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Login
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Azure CLI ACR Login
        run: az acr login --name pratsa

      - name: Build Docker image
        run: |
          docker build -t dietplan .
          docker tag dietplan pratsa.azurecr.io/dietplan:${{ github.sha }}

      - name: Push Docker image
        run: docker push pratsa.azurecr.io/dietplan:${{ github.sha }}
        
      - name: Deploy to AKS
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}
          az aks get-credentials --resource-group vc9071 --name pratsa --overwrite-existing
          kubectl set image deployment/dietplan dietplan=pratsa.azurecr.io/dietplan:${{ github.sha }}